// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Molecule.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Molecule.Persistence.Migrations
{
    [DbContext(typeof(MoleculeDbContext))]
    partial class MoleculeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Molecule.Domain.Bouquet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Bouquets");
                });

            modelBuilder.Entity("Molecule.Domain.BouquetFlour", b =>
                {
                    b.Property<Guid>("BouquetsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FloursId")
                        .HasColumnType("uuid");

                    b.Property<int>("BouquetId")
                        .HasColumnType("integer");

                    b.Property<int>("FlourId")
                        .HasColumnType("integer");

                    b.HasKey("BouquetsId", "FloursId");

                    b.HasIndex("FloursId");

                    b.ToTable("BouquetFlour");
                });

            modelBuilder.Entity("Molecule.Domain.Flour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Flours");
                });

            modelBuilder.Entity("Molecule.Domain.BouquetFlour", b =>
                {
                    b.HasOne("Molecule.Domain.Bouquet", null)
                        .WithMany()
                        .HasForeignKey("BouquetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Molecule.Domain.Flour", null)
                        .WithMany()
                        .HasForeignKey("FloursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
